### ISSUE TITLE
Code for pitch accent prediction.

### ISSUE THREAD

**Issue by Chunngai** [olety/japanese-pitch-accent-resources#5]
Hello. Great resources in the repo.

In addition to online websites for pitch search, do you know any software or repo for pitch accent prediction?

Thank you!

**Comment by olety** [comment]
@Chunngai I didn't use it myself, but Praat might be useful if you're talking about detecting PA based on the sounds.

https://www.japanese-pronunciation.com/eng/movie/accent1/

If you wanna predict them with a ML model might wanna check out this, although it's really old; might be better to just train a bunch of models yourself and see which one performs better.
https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=6c80f96e4ad3622afccf37234b9b1eadc03232c5

**Comment by Chunngai** [comment]
@olety Hello. Thanks for your reply.

What I am looking for is a tool for predicting pitch accents for texts.

Some websites listed in the "Online dictionaries" section of the repo partially satisfy my need, such as [OJAD](https://www.gavo.t.u-tokyo.ac.jp/ojad/phrasing/index), [JPDB](https://jpdb.io/) and [Jotoba](https://jotoba.de/).

Among them, what [OJAD](https://www.gavo.t.u-tokyo.ac.jp/ojad/phrasing/index) does is totally what I need. However, it seems that it does not performs well. For example, it predicts the pronunciation of the sentence "今ご飯食べてる" as "こんごはんたべてる", which is obviously not accurate. Since I want to use PA prediction for Japanese learning, I need something with better accuracy.

On the other hand, [JPDB](https://jpdb.io/) and [Jotoba](https://jotoba.de/) produce higher accuracy in pronunciation annotation. However, these sites convert words into their base forms. For example, the sentence above will be converted to "今　ご飯　食べる", but what I need is the PA of the complete sentence.

I've done some searching, but it seems that no tools satisfy my need. As you mentioned, training ML models for prediction is another choice.

**Comment by olety** [comment]
@Chunngai I mean I wouldn't call it prediction, there are pretty rigid accent rules in the Tokyo dialect/標準語 so it's more like detection or sentence analysis but I got your point. Sorry, I am not aware of a tool that would satisfy your need fully, maybe someone else could comment on this.

Tbh I would recommend just going through the [Dogen's](https://www.patreon.com/dogen) course or some other course in the list and learning the rules yourself, that ensures that you are able to analyze the sentences without a crutch.

As for OJAD's [Suzuki-kun](https://www.gavo.t.u-tokyo.ac.jp/ojad/phrasing/index), if you write いまご飯食べてる it gives the correct output.

**Comment by Chunngai** [comment]
@olety Thanks for your suggestions!!!
